language: node_js
node_js:
  - "10.15.3"
addons:
    code_climate:
        repo_token: a3a82927ac510ca4190e345a00f666dc47bb81a3497d57050d2de5db22e54c57
script: istanbul cover node_modules/mocha/bin/_mocha -- -R spec
before_script:
  - npm install codeclimate-test-reporter istanbul -g
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
install:
  - npm install
script:
  - npm run test
after_success: 
  - npm run coverage
