env:
  global:
  - SECRET=DevCTrainingWithAndelaMyPasswordNiJoor
  - USER=postgres
  - HOST=localhost
  - DB=teamwork
  - PASSWORD='atanda508'
  - dbPORT=5432

language: node_js

node_js:
  - 10
